/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.time.*;
import java.time.temporal.*;


public void rtc(GTimer source) { //_CODE_:clock:543544:
  SimpleDateFormat fmdt = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
  SimpleDateFormat fmtm = new SimpleDateFormat("00:mm:ss");
  Date dt = new Date(System.currentTimeMillis());
  lblClock.setText(fmdt.format(dt));
  if (startTime != null && formIndex == START_FORM) {
    Duration duration = Duration.between(LocalDateTime.now(), startTime);
    Long period = Math.abs(duration.toMillis()); 
    Long seconds =  (Long.divideUnsigned(period, new Long(1000)));
    if (config.secs > 0) {
      Float a = new Float(seconds);
      Float b = new Float(config.secs);
      Float c =  (a / b);
      Float d = (c * 100);
      lblPecentual.setText(d.intValue() + "%");
      if (d.intValue() == 100) {
        formIndex = DONE_FORM;
      }
    }
    lblTimer.setText(fmtm.format(period));
  }
} //_CODE_:clock:543544:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GREEN_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("BPMLab Remote Control");
  viewConnection = new GView(this, 10, 10, 250, 130, JAVA2D);
  viewArena = new GView(this, 270, 10, 690, 470, JAVA2D);
  viewConsole = new GView(this, 10, 150, 250, 330, JAVA2D);
  viewLog = new GView(this, 10, 491, 950, 221, JAVA2D);
  viewFileSystem = new GView(this, 972, 12, 290, 702, JAVA2D);
  clock = new GTimer(this, this, "rtc", 1000);
  clock.start();
}

// Variable declarations 
// autogenerated do not edit
GView viewConnection; 
GView viewArena; 
GView viewConsole; 
GView viewLog; 
GView viewFileSystem; 
GTimer clock; 
