/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void rtc(GTimer source) { //_CODE_:clock:543544:
 updateTimes();
} //_CODE_:clock:543544:

synchronized public void winDraw(PApplet appc, GWinData data) { //_CODE_:analyseWindow:818268:
  appc.background(235);
  appc.stroke(0);
  appc.strokeWeight(2);
} //_CODE_:analyseWindow:818268:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(true);
  G4P.setGlobalColorScheme(GCScheme.GOLD_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("BPMLab Remote Control");
  viewConnection = new GView(this, 10, 10, 250, 130, JAVA2D);
  viewArena = new GView(this, 270, 10, 690, 470, JAVA2D);
  viewConsole = new GView(this, 10, 150, 250, 330, JAVA2D);
  viewLog = new GView(this, 10, 491, 950, 221, JAVA2D);
  viewFileSystem = new GView(this, 972, 12, 290, 702, JAVA2D);
  clock = new GTimer(this, this, "rtc", 1000);
  clock.start();
  analyseWindow = GWindow.getWindow(this, "Anallyze BPM File", 0, 0, 1024, 640, JAVA2D);
  analyseWindow.noLoop();
  analyseWindow.setActionOnClose(G4P.CLOSE_WINDOW);
  analyseWindow.addDrawHandler(this, "winDraw");
  viewFileAnalyze = new GView(analyseWindow, 15, 9, 269, 124, JAVA2D);
  viewFileEstat = new GView(analyseWindow, 13, 144, 270, 167, JAVA2D);
  view3 = new GView(analyseWindow, 296, 9, 373, 302, JAVA2D);
  analyseWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GView viewConnection; 
GView viewArena; 
GView viewConsole; 
GView viewLog; 
GView viewFileSystem; 
GTimer clock; 
GWindow analyseWindow;
GView viewFileAnalyze; 
GView viewFileEstat; 
GView view3; 
